
apiVersion: v1
kind: Service
metadata:
  name: adding-numbers-api-service
  labels:
    app: adding-numbers-api
spec:
  type: LoadBalancer
  selector:
    app: adding-numbers-api
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  sessionAffinity: ClientIP
